### ISSUE TITLE
Keeping track of current status

### ISSUE THREAD

**Issue by luisorbaiceta** [fastify/website-next#11]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I think it is important to know where we are, what has been done is obvious (great work btw!), but what needs to be done to have this ready. A good way would be to open issues for major things so any contributor can give us a hand and knows where to start.

### WIP

  - [ ] Docs
    - [ ] Fix darkmode font color
  - [ ] Ecosystem
  - [ ] Benchmarks

**Comment by lachlancollins** [comment]
@luisorbaiceta I've been working on the finalised proposal with @Xhale1, you can expect it very soon :)

**Comment by luisorbaiceta** [comment]
That's great! Do you think you can make that report anyway? I've seen some custom pages (like `ecosystem`) are still blank and haven't seen any branched work with them. A quick check list in this issue description would be amazing!

**Comment by luisorbaiceta** [comment]
Hi @lachlancollins @Xhale1! I was wondering if this is something you plan to keep on with

**Comment by Eomm** [comment]
Here is a fresh start for this project https://github.com/fastify/website-next/issues/32
