### ISSUE TITLE
Ecosystem page

### ISSUE THREAD

**Issue by Eomm** [fastify/website-next#21]
We need to implement the Ecosystem page: 

https://www.fastify.io/ecosystem/

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/11404065/209004373-27e03eab-f929-47aa-aa9c-2982960243a2.png">

## Challenges

- [ ] Generate the plugin list
- [ ] Nice to have: add a filter under the `Name` and `Description` columns

Note that downloading the https://github.com/fastify/fastify/blob/main/docs/Guides/Ecosystem.md file is not in the scope of this task. You can assume that you have the markdown file in one directory. So, starting from there, you should be able to write a script that generates a JSON file that the new ecosystem page can render.

## Tips

- Here is a snippet that parses the Ecosystem page and extracts the plugin list  https://github.com/fastify/website/blob/master/src/scripts/processReleases.js#L316

**Comment by fanciulli** [comment]
Looks like a good first issue for me

**Comment by Eomm** [comment]
Top! When you have something to show, feel free to open a draft PR - don't wait till the end 👍🏽

**Comment by fanciulli** [comment]
Hi! Just posted my very first PR. 
It's part of the work but should be enough to take a look and decide some aspects (stylign, proper website organization etc..)
Will continue during these days.
