### ISSUE TITLE
Benchmarks page

### ISSUE THREAD

**Issue by Eomm** [fastify/website-next#22]
Migrate the benchmarks web page:

https://www.fastify.io/benchmarks/

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/11404065/209006752-2a057e38-41f9-4324-9c49-3eed836bc290.png">

## Challanges

- [ ] Download the [bench results](https://github.com/fastify/website/blob/master/src/scripts/downloadBenchmarks.js#L7)
- [ ] Show the data in a nice way

### In scope

Sometimes the bench repo doesn't work as shown in the image
[Here the broken result file](https://raw.githubusercontent.com/fastify/benchmarks/08b85517798c79a887e331df557d0ec74dafb68c/benchmark-results.json)

In this case, we should ignore the results and go back in the file history to get the last valid one. Here [a valid file example](https://raw.githubusercontent.com/fastify/benchmarks/17b08d127a29c9dfec07f88c49019095b12ffe70/benchmark-results.json)

This should work to get it:

- `GET /repos/{owner}/{repo}/commits?path={file_path}`
- `GET /repos/{owner}/{repo}/git/commits/{commit_sha}`
- `GET /repos/{owner}/{repo}/git/blobs/{blob_sha}`
- validate the file or next commit sha

**Comment by fanciulli** [comment]
I can work on this

**Comment by Eomm** [comment]
Go for it!

**Comment by fanciulli** [comment]
@Eomm is it ok if the implementation is like this:

1. MDX page downloads the link to data
2. Checks if data is corrupted
3. If not, displays the data
4. If corrupted searches for a version of the file which is ok (max depth of 10)

I'm taking the assumption that the file is unfrequently corrupted and that and history of 10 past revision will provide a valid file.

What do you think about this?

**Comment by fanciulli** [comment]
Giving a suggestion for the data visualization: what about [this](https://www.chartjs.org/docs/latest/samples/other-charts/polar-area-center-labels.html)?

**Comment by Eomm** [comment]
> MDX page downloads the link to data

The page would be very heavy - we should aim to be a static website (we don't need real time updates). So the mdx page should just show a json, meanwhile the benchmark data are fetched during build time.

So I would expect a `script/download-banchmark` that produces the json file that will be consumed by the mdx page.

> I'm taking the assumption that the file is unfrequently corrupted and that and history of 10 past revision will provide a valid file.

Yes, totally fair to retry max 10 times - otherwise the script will throw an error and the website build will fail

> Giving a suggestion for the data visualization: what about [this](https://www.chartjs.org/docs/latest/samples/other-charts/polar-area-center-labels.html)?

I would keep the bar visualization for now

**Comment by fanciulli** [comment]
OK, sounds good. Will implement

**Comment by fanciulli** [comment]
@Eomm Some additional questions:

1. Original page has fewer framework comapred to the JSON file. Are we sticking with those in the original page or display all?
2. The Github icon on each card points to the project repo which is not available in the JSON. Not a problem if we stick to a subset (will add manually) but should be fetched elsewhere if we make a dynamic thing out of this.
