### ISSUE TITLE
Contribute page

### ISSUE THREAD

**Issue by Eomm** [fastify/website-next#23]
Implement the contribute page:

https://www.fastify.io/contribute/

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/11404065/209005722-83d6eb18-ce69-43ab-b933-f678ff443996.png">

## Challanges

- [ ] Integrate a plugin to get the `Good first issues`

## Tips

What would I do?
I would look for an existing Docusaurus plugin or I would build it (instead of integrating custom logic here)

Note that the actual code from the old website should be easily migrated: https://github.com/fastify/website/blob/master/src/website/content/js/contribute.js

**Comment by fanciulli** [comment]
Can I take ownership of this?

**Comment by Eomm** [comment]
Yeah, sure!

**Comment by Eomm** [comment]
PS: here there is a discussion on this topic:

- https://github.com/mercurius-js/mercurius/issues/941

**Comment by fanciulli** [comment]
Ok. I'll take a look at the issue in the weekend, had busy days lately. Sorry!

**Comment by fanciulli** [comment]
@Eomm need to step back in this because I have very few time to work on it. Will take ownership back in the future if no one worked on this
