### ISSUE TITLE
stick to current website design

### ISSUE THREAD

**Issue by luisorbaiceta** [fastify/website-next#3]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

We should try to stick as much as possible to the current website design and iterate from there. As tempting as using a new tech stack and implementing new features can be, we have to think about the end user that is already familiar with the current website. Let's not forget that the goal of the site should just be update the stack and make it more maintainable in the long term

**Comment by Xhale1** [comment]
I'm not sure I fully agree.

Improved design, usability, and functionality are amongst some of my core proposals for this upgrade, not only maintenance (and it seemed like other members agreed). It seems to me that if we're changing the tech stack, we should do it for a good reason (in this case additional features adds to the value proposition)

That said, we can pretty easily imitate the original design while also using new features included in this tech demo.

If you're referring to just the landing page and other non-docs pages, we could do one of two things
- Use the existing site and host the new docs under a `/docs` path
- Recreate those pages as close to the original design as we can in react, and serve them through docusaurus alongside the new docs

**Comment by lachlancollins** [comment]
Yep I fully agree that the original non-docs pages should be imitated as much as possible - I'm not a designer so I would be mimicking the originals anyway. The docs themselves will obviously have a large theme overhaul.

**Comment by Xhale1** [comment]
Yea, I should have clarified. I totally agree that non-docs pages should be imitated as closely as possible. That begs the question though, _if_ we were to move forward with docusaurus, how would we handle the remainder of the landing site?

I suppose we could either fully convert to react & docusaurus, or host two sites (one being the existing landing page, and one for docs).

**Comment by luisorbaiceta** [comment]
> I suppose we could either fully convert to react & docusaurus, or host two sites (one being the existing landing page, and one for docs).

IMO the best approach would be to fully convert. Maintaining two sites can become clunky over time

**Comment by lachlancollins** [comment]
It shouldn't be much effort to convert them :) I've published some placeholder pages for them already (I won't work on them urgently though).

**Comment by mcollina** [comment]
My _preference_ would be to keep the existing site as-is as possible and port it to Elevently.

I think a landing page is needed - Docusaurus does not cater well to that.

**Comment by lachlancollins** [comment]
From my testing I think Docusaurus does handle non-docs pages well - [this file](https://github.com/fastify/website-next/blob/main/src/pages/index.js) is the source of the landing page, and can be customised however we want it. Same with all the other top-level pages such as [Ecosystem](https://github.com/fastify/website-next/blob/main/src/pages/Ecosystem.js). With the current demo I haven't migrated any of these over because I wanted to focus on the docs.

**Comment by jsumners** [comment]
As stated in the original thread: `fastify.io` is more than just a documentation site. Whatever is done needs to support generating:

+ https://www.fastify.io
+ https://www.fastify.io/ecosystem/
+ https://www.fastify.io/benchmarks/
+ https://www.fastify.io/contribute/

We also want to eventually support pinning of organizations that use Fastify.

**Comment by o-t-w** [comment]
This is a shame as there are a few objective issues with the current landing page: 
- 50-75 characters per line is the well established range for [easily-readable paragraph text](https://accessibility.digital.gov/visual-design/typography/). On laptop/desktop the paragraphs in the current design have far more characters than this. 
- The button text does not pass AA color contrast
- The button text is not vertically centered (there is equal top and bottom padding but the `line-height` makes it visually uncentered)

**Comment by jsumners** [comment]
@o-t-w no one said they couldn't be improved. We said the pages need to be retained and supported by whatever system implements the website generation.

**Comment by luisorbaiceta** [comment]
> This is a shame as there are a few objective issues with the current landing page: 
> - 50-75 characters per line is the well established range for [easily-readable paragraph text](https://accessibility.digital.gov/visual-design/typography/). On laptop/desktop the paragraphs in the current design have far more characters than this. 
> - The button text does not pass AA color contrast
> - The button text is not vertically centered (there is equal top and bottom padding but the `line-height` makes it visually uncentered)

Hi @o-t-w, thanks for highlighting this! As @jsumners says, the intend of this does not include current usability or accessibility problems of course. Do you think you can open a separate issue or send a PR so we can keep track of it?

**Comment by Eomm** [comment]
Here is a fresh start for this project https://github.com/fastify/website-next/issues/32
