### ISSUE TITLE
[CRITICAL] Recovery from a force-push

### ISSUE THREAD

**Issue by HassanBahati** [fastify/website-next#36]
Hi @Eomm, I am opening this issue because i need help with addressing a force-push that just happened.

I was trying to open a pull request to address an issue #34 through  #35. My fork showed there was a merge conflict so as i tried to solve it by following the leads given to undo 1 commit. Which i thought would undo my commit but instead triggered a force-push from [f1ba71b](https://github.com/fastify/website-next/commit/f1ba71bd08111b2bcd6cb7d0a7065c4668a499ca) to [4e3f356](https://github.com/fastify/website-next/commit/4e3f3565f2f305b58e7aae0bc0bb4c2e34b1b919) .

Kindly help.

**Comment by climba03003** [comment]
There are no way to rescue from `force-push`, it replace all the data in git history.
That is also why `protected branch` also ban `force-push`.

**Comment by HassanBahati** [comment]
Actually hadn't noticed its what was happening, my fork showed i had conflicts , so i clicked the update fork button and it showed i had reverted one commit back.

**Comment by HassanBahati** [comment]
My kindest apologies, my fork showed there were merge conflicts as i tried opening a pull request. So i clicked to resolve the conflicts and was then notified a force-push had happened.

**Comment by climba03003** [comment]
If the revert is done through `Github`, you may check if your local computer keep the data.
When you didn't sync the commit from `remote` to `local`, it should be keep in `local`.

**Comment by HassanBahati** [comment]
> If the revert is done through `Github`, you may check if your local computer keep the data. When you didn't sync the commit from `remote` to `local`, it should be keep in `local`.

Yes it was through GitHub, where i was trying to update my fork so as to resolve merge conflicts.

**Comment by HassanBahati** [comment]
Am so sorry about this , my kindest apologies. I didn't mean to submit a force-push but rather as i was updating my fork to resolve a flagged merged conflict in the background a force-push happened

**Comment by Eomm** [comment]
Hey,
don't panic 😄

1) there is no reason to apologise: the force push has been done against your repository so nothing has changed in `website-next`. So, I'm sorry that you may have lost your changes

2) in your local environment, you can try:

```
git reflog
// show your local history, even lost commits

git checkout <commit SHA you want restore>
git checkout -b checkpoint
```

3) I'm old-style dev: I keep my fork in sync by command line. This guide [is complete](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-branch-from-the-command-line)
I often force push from `upstream/main` to my fork `origin/main` - I never push code in my `main` branch because its ownership is on the `upstream`


Closing as "not an issue" for the `website-next` repo 👍🏽

**Comment by HassanBahati** [comment]
> Hey, don't panic smile
> 
>     1. there is no reason to apologise: the force push has been done against your repository so nothing has changed in `website-next`. So, I'm sorry that you may have lost your changes
> 
>     2. in your local environment, you can try:
> 
> 
> ```
> git reflog
> // show your local history, even lost commits
> 
> git checkout <commit SHA you want restore>
> git checkout -b checkpoint
> ```
> 
>     3. I'm old-style dev: I keep my fork in sync by command line. This guide [is complete](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-branch-from-the-command-line)
>        I often force push from `upstream/main` to my fork `origin/main` - I never push code in my `main` branch because its ownership is on the `upstream`
> 
> 
> Closing as "not an issue" for the `website-next` repo 👍🏽

I was scared that the force-push had deleted a couple of files in the main branch.

The reflog steps work like magic :smile: 

Thank you @Eomm for the leads.

I have reflogged and [here](https://github.com/HassanBahati/website-next/tree/recover-files) is a copy after recovery of the files on my branch
