### ISSUE TITLE
Configure GitHub Pages to serve the website's build

### ISSUE THREAD

**Issue by lachlancollins** [fastify/website-next#4]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi, I believe the GitHub Pages settings need to be changed to serve from a custom subdomain. A possible option is something like `fastify-website-next.github.io`. It also needs to select the gh-pages branch. Here's the interface I see on a personal repo, but it's possible it could be different for organisation repos.

![image](https://user-images.githubusercontent.com/1667261/143427934-e5cdd99b-93b3-447f-a249-eb5cdb38f543.png)

**Comment by mcollina** [comment]
The website is available at https://fastify.github.io/website-next/

**Comment by lachlancollins** [comment]
Yep okay, it's not loading correctly as it doesn't like the `/website-next/` path. I'll try following its suggestion, hopefully it doesn't break compatibility.

![image](https://user-images.githubusercontent.com/1667261/143428600-106ccd26-da00-462d-bc28-88cea3dc8c47.png)

**Comment by lachlancollins** [comment]
Great, working now at https://fastify.github.io/website-next/ - thanks!
