### ISSUE TITLE
Broken Organizations links

### ISSUE THREAD

**Issue by Eomm** [fastify/website-next#55]
On the live website: https://fastify.github.io/website-next/

The homepage organization section is broken:

1. Images:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/11404065/213878161-90cf8135-1f09-4399-9135-a4b46c1df1a2.png">

2. Links:

<img width="531" alt="image" src="https://user-images.githubusercontent.com/11404065/213878192-c6d247ce-0c7c-40b6-9a9c-4c5812dea797.png">

We must use the `<Link` component and solve the image issue as well (not sure how)

**Comment by HassanBahati** [comment]
@Eomm let me look into
