### ISSUE TITLE
feat(icon): logo of website in footer

### ISSUE THREAD

**Issue by AugustinMauroy** [fastify/website-next#57]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I propose to replace the text by the logo of the site in question.

<img width="1440" alt="Capture d’écran 2023-01-25 à 11 44 37" src="https://user-images.githubusercontent.com/97875033/214543296-ca436aba-632f-4cd4-a914-b4c060475171.png">

### Motivation

It makes it more "beautiful" (this is subjective). And around it makes the footer smaller so lighter on the brain.

### Example

We can use Font Awesome

**Comment by Eomm** [comment]
We need to change the footer text paragraph as well

Would you like to send a Pull Request to address this issue?

**Comment by AugustinMauroy** [comment]
> We need to change the footer text paragraph as well

A text idea?

**Comment by AugustinMauroy** [comment]
There are no compulsory links (those of the opens-f.)

**Comment by Eomm** [comment]
I mean this one:

> Fastify, Copyright © 2016-2023 [OpenJS Foundation](https://openjsf.org/) and [The Fastify team](https://github.com/fastify/fastify#team), Licensed under [MIT](https://github.com/fastify/fastify/blob/master/LICENSE)
