### ISSUE TITLE
Scripts to import documentation from fastify/fastify

### ISSUE THREAD

**Issue by lachlancollins** [fastify/website-next#6]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Following on from fastify/fastify#3492, I think we have everything we need to import documentation into this project.

For v3 (current):
- The /docs/ folder from `main` branch needs to be cloned into /docs/ locally.
- While we restructure these docs, we should use `docs-reorg` branch instead (but can easily switch `main` once it is merged).

For v2:
- The /docs/ folder from `2.x` branch needs to be cloned into /versioned_docs/version-v2/ locally.

For v1:
- The /docs/ folder from `1.x` branch needs to be cloned into /versioned_docs/version-v1/ locally.

@luisorbaiceta is this something you are able to work on? Thanks!

**Comment by luisorbaiceta** [comment]
I already have most of the work done. I will need to add some more logic though as separating some of the docs to a nested path called `versioned_docs` and the latest version to a root level folder will add complexity

**Comment by Eomm** [comment]
Here is a fresh start for this project https://github.com/fastify/website-next/issues/32
