### ISSUE TITLE
Typescript support 

### ISSUE THREAD

**Issue by AugustinMauroy** [fastify/website-next#73]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I propose to implement typescript in the project.

### Motivation

It's better for security.

### Ref:

https://docusaurus.io/docs/typescript-support

**Comment by Eomm** [comment]
Whenever the majority of the maintainers of this repo will ask for it, we can do it.

Till then: I'm not keen to migrate this repo to TS nor to review a PR
I maintain it in my free time, and I'm already out of my comfort zone here
